name: Build PyArmor Linux

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PyArmor
        run: pip install pyarmor

      - name: Run PyArmor build
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4  # <----- ВОТ ЭТО ВАЖНО
        with:
          name: protected-bot
          path: dist/
